cursor #f0dee0
cursor_text_color #d6c2c3

foreground            #f0dee0
background            #191112
selection_foreground  #000000
selection_background  #f8bbd9
url_color             #e91e63

color0   #191112
color1   #ff1818
color2   #51e91e
color3   #ffcc0a
color4   #f42e5c
color5   #6b0024
color6   #e91e63
color7   #f4dbe3
color8   #97838a
color9   #ff585f
color10  #8aff63
color11  #ffde63
color12  #ff4282
color13  #ff6398
color14  #ff9bbd
color15  #fff3f7
